#!/usr/bin/env bash
# Installs adb into a user-local prefix without root.
#
# The UNO Q factory image has no adb and sudo is password-gated, so instead of
# 'apt install adb' we download the Debian packages (which needs no privileges)
# and unpack them under tools/root, then generate a wrapper that points the
# dynamic linker at them.
set -euo pipefail

ROOT=/home/arduino/qcluster
DEB="$ROOT/tools/deb"
PREFIX="$ROOT/tools/root"
BIN="$ROOT/tools/bin"

PACKAGES=(
  adb
  android-libbase android-libboringssl android-libcutils
  android-liblog android-libziparchive
  libbrotli1 liblz4-1 libzstd1 libusb-1.0-0 libprotobuf32t64
)

rm -rf "$PREFIX"
mkdir -p "$DEB" "$PREFIX" "$BIN"

echo "== downloading $( echo "${PACKAGES[@]}" | wc -w ) packages =="
(cd "$DEB" && apt-get download "${PACKAGES[@]}")

echo "== unpacking =="
for deb in "$DEB"/*.deb; do
  dpkg-deb -x "$deb" "$PREFIX"
done

cat > "$BIN/adb" <<EOF
#!/bin/sh
# Generated by scripts/fetch-adb.sh - adb from Debian packages, no root install.
R=$PREFIX
LIBS="\$R/usr/lib/aarch64-linux-gnu:\$R/usr/lib/aarch64-linux-gnu/android"
exec env LD_LIBRARY_PATH="\$LIBS\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" \\
  "\$R/usr/lib/android-sdk/platform-tools/adb" "\$@"
EOF
chmod +x "$BIN/adb"

"$BIN/adb" version
echo "== adb installed at $BIN/adb =="
